### PR TITLE
Make logging depend on DEBUG setting instead of always being in debug mode.

### PR DESCRIPTION
**Pull request by Hoid**

### CODE REVIEW

**Comment by pj-linebaugh** [comment]
Can you make it so that LOG_LEVEL can be set in the Helm chart and have that value trickle down to the container?   That way other log levels can be set instead of just info and debug.  Unsure if that DEBUG variable does anything else other than set the log level.  It might not be needed, but if it does do something else maybe if DEBUG is set to true then it can override whatever value is set for LOG_LEVEL.

**Comment by Hoid** [comment]
> Can you make it so that LOG_LEVEL can be set in the Helm chart and have that value trickle down to the container? That way other log levels can be set instead of just info and debug. Unsure if that DEBUG variable does anything else other than set the log level. It might not be needed, but if it does do something else maybe if DEBUG is set to true then it can override whatever value is set for LOG_LEVEL.

Done :)

**Comment by Hoid** [comment]
Ah wait, missed something. I'll fix it real quick.

**Comment by Hoid** [comment]
Done. It should be good to go now @pj-linebaugh

**Review by pj-linebaugh — APPROVED** [review]
Looks good.  The variable will also need to be added to the Helm chart.

**Pull request merged**
