### PR TITLE
develop to master

### PR DESCRIPTION
**Pull request by n0mn0m**

### CODE REVIEW

**Comment by n0mn0m** [comment]
@ismagilani I think the `BRAND` env variable got changed in `master` earlier this week. I think it's more helpful to remove it so that it is always set to a know provided value. Thoughts?

@pj-linebaugh can we get `helxplatform/appstore:develop-v1.1.39` in `helx-dev` for testing?

@mbrightman once that is in `helx-dev` can we do a new round of testing?

**Comment by ismagilani** [comment]
> @ismagilani I think the `BRAND` env variable got changed in `master` earlier this week. I think it's more helpful to remove it so that it is always set to a know provided value. Thoughts?
> 
> @pj-linebaugh can we get `helxplatform/appstore:develop-v1.1.39` in `helx-dev` for testing?
> 
> @mbrightman once that is in `helx-dev` can we do a new round of testing?

@n0mn0m do you mean DJANGO_SETTINGS in Dockerfile?

**Comment by n0mn0m** [comment]
> @n0mn0m do you mean DJANGO_SETTINGS in Dockerfile?

Whoops! Yes, sorry was thinking of the `brand` term we use in other docs/code.

**Comment by ismagilani** [comment]
> > @n0mn0m do you mean DJANGO_SETTINGS in Dockerfile?
> 
> Whoops! Yes, sorry was thinking of the `brand` term we use in other docs/code.

I am fine removing it as long as there are no side effects

**Comment by pj-linebaugh** [comment]
I think having DJANGO_SETTINGS default to 'cat' in the Dockerfile is the way to go.  I'll update helx-dev with the new appstore image version.

**Comment by ismagilani** [comment]
> I think having DJANGO_SETTINGS default to 'cat' in the Dockerfile is the way to go. I'll update helx-dev with the new appstore image version.

How is DJANGO_SETTINGS in Dockerfile different from djangoSettings in chart values file?

**Comment by n0mn0m** [comment]
The side effect would be that if the `bin/appstore` doesn't source an environment variable we would know that a lot faster.

@pj-linebaugh is there a benefit to hard coding that as the default? Seems like this setting caused more confusion than help earlier in the week. Not opposed to using `cat`, but seems like it leaves room for the env variable to not be set right by the caller and left unknown for a while due to the default hiding that fact.

**Comment by pj-linebaugh** [comment]
If it isn't needed at all then we should get rid of it.  'cat' (djangoSettings default value) is used in the helm chart to create the entrypoint command so it is redundant.

**Pull request merged**
