### PR TITLE
Decouple UI

### PR DESCRIPTION
**Pull request by frostyfan109**
- Removed `helx-ui` builder image from Dockerfile
- Remove `populate_env` script (`env.json` is created by the ui chart, so we only have one populate_env script now)
- Removed the `/helx` route
- Redirect the `/` and `/default` routes to `/helx`
- Add `dockstore_app_specs_dir_url` to context api endpoint

### CODE REVIEW

**Review by pj-linebaugh — APPROVED** [review]
If "DOCKSTORE_APP_SPECS_DIR_URL" isn't being used anymore then it probably also needs to be removed from appstore-chart.

**Comment by frostyfan109** [comment]
@pj-linebaugh  It actually wasn't in the AppStore chart, it's computed using multiple tycho-related values. So no need to remove anything there

**Comment by pj-linebaugh** [comment]
https://github.com/helxplatform/appstore-chart/blob/213f86d6b76eb98f19d606bc5eb83928dedda9d4/templates/deployment.yaml#L449

**Comment by frostyfan109** [comment]
> https://github.com/helxplatform/appstore-chart/blob/213f86d6b76eb98f19d606bc5eb83928dedda9d4/templates/deployment.yaml#L449

My bad, removed now

**Pull request merged**
