### PR TITLE
django version 3.2

### PR DESCRIPTION
**Pull request by Acharya-Saurya**
[#791](https://github.com/helxplatform/development/issues/791)

### CODE REVIEW

**Comment by ismagilani** [comment]
@Acharya-Saurya do we know why this build is failing? @muralikarthikk can you please help Saurya figure this out?

**Comment by cnbennett3** [comment]
> @Acharya-Saurya do we know why this build is failing? @muralikarthikk can you please help Saurya figure this out?
@ismagilani , @Acharya-Saurya, @muralikarthikk 
There's an issue with the build server at the moment that's affecting all builds. I'm working on it now. I'll re-run the build when it's fixed.

**Comment by ismagilani** [comment]
Thanks for the update @cnbennett3

**Review by ismagilani — APPROVED** [review]

**Comment by ismagilani** [comment]
@muralikarthikk please review.  @frostyfan109 please merge to develop after Murali's approval and test the develop build on a helx domain like eduhelx-dev.

**Comment by muralikarthikk** [comment]
Looks good to me.

**Review by muralikarthikk — APPROVED** [review]

**Pull request merged**
