### PR TITLE
Feature/jenkinsfile standardization

### PR DESCRIPTION
**Pull request by cschreep**
Adding Makefile and Jenkinsfile

### CODE REVIEW

**Comment by cschreep** [comment]
@n0mn0m I added a VERSION file in the top-level directory. I'm not sure if there's a better location where that info should be tracked within the repo?

**Comment by n0mn0m** [comment]
What are your thoughts on https://github.com/helxplatform/appstore/pull/101

**Comment by cschreep** [comment]
I think that's great, I can rebase this branch off of that one to add the Jenkinsfile using the existing Makefile in there

**Comment by n0mn0m** [comment]
@cschreep this won't work without the `-e` due to how Django introspects `INSTALLED_APPS` and expects them to be available. Happy to walkthrough that further, but it was a pain point when working on this and something I would want to work on over time, or look at better ways to handle this.

**Comment by n0mn0m** [comment]
@cschreep you will want to rebase one more time, but this should be good to go now.

**Pull request closed without merging**
