### PR TITLE
Dockstore branch setting helx UI

### PR DESCRIPTION
**Pull request by frostyfan109**
Restructures static assets and updates populate_env script

### CODE REVIEW

**Comment by waTeim** [comment]
BRANDS          := braini cat heal restartr scidas eduhelx argus
    BRANDS          := braini bdc heal restartr scidas eduhelx argus

Should `tracs` be in this list or is that for later?

**Comment by frostyfan109** [comment]
Yes it probably should be

**Comment by muralikarthikk** [comment]
> ```
> BRANDS          := braini cat heal restartr scidas eduhelx argus
> BRANDS          := braini bdc heal restartr scidas eduhelx argus
> ```
> 
> Should `tracs` be in this list or is that for later?

tracs related changes are on ohdsi_in_a_pod branch. This should be merged first i guess.

**Review by muralikarthikk — APPROVED** [review]

**Comment by muralikarthikk** [comment]
I think we should update the helx-ui image in the Dockerfile, if there is a latest one.

**Pull request merged**
