### PR TITLE
Add .env file to .gitignore

### PR DESCRIPTION
**Pull request by Hoid**
For anyone affected by this change, note that the `.env` will be deleted when you pull after this commit, but you can find it at `.env.default`. This file is copied to `.env` if that file doesn't exist while using `make`.

### CODE REVIEW

**Comment by Hoid** [comment]
I'm in the process of updating the Makefile so that it will copy the `.env.sample` file to `.env` if `.env` doesn't exist, which would solve the build error currently.

**Comment by Hoid** [comment]
Okay should be good now. What I did is take the previous `.env` file in the repo and change its name to `.env.default` (note: different from `.env.sample`). The Makefile will now check to see whether the `.env` file is present, and if not will copy the `.env.default` file to `.env`. This will make sure that new builds on machines in pipelines will have an `.env` present for the `make` commands but also added `.env` to `.gitignore`, so that you can change yours locally without seeing your changes in the git working tree. 

I've tested `make clean` and `make install` locally, as well as building and pushing the image followed by applying the image to my k8s deployment. All work as expected.

**Comment by pj-linebaugh** [comment]
This sounds reasonable to me.  I think you should also go ahead and remove the .env from the repo.

**Comment by Hoid** [comment]
> This sounds reasonable to me. I think you should also go ahead and remove the .env from the repo.

This PR will remove it (well actually it just renames it to `.env.default` but it won't be there after this)

**Comment by pj-linebaugh** [comment]
Ah, just reread what you said and noticed you said you renamed it.  Doh!  I should have gone through the review process, missed the first line in my quick look.

**Review by pj-linebaugh — APPROVED** [review]

**Review by muralikarthikk — APPROVED** [review]

**Pull request merged**
