### PR TITLE
Update react serving and cleanup structure

### PR DESCRIPTION
**Pull request by n0mn0m**
While working on the auth flow for the react frontend I was running into some form, route and data conflict behaviors. Dug in and cleaned things up to help support separation of django apps, templates, data, forms etc.

- Moved templates into per django app namespace folders
- Removed unused settings. Restructured settings for clarity.
- Move product model into package namespace
- Fix login form functionality
  - Login form needs support from a backing view when embedded in
    an app template. Setup the Index view in core to support the
    core template and url paths
- Cleanup url paths
  - Move urls into app namespace
  - Use allauth urls without redirect, and handle login via view
    inheritance in per app package functionality
- Run formatter on new and modified files
- Fix regex url deprecation warning in api package
- Move 4xx, 5xx templates into top level namespace and remove
  url handler functions since Django will serve these templates
  by default
- Remove unused form code
- Replace bootstrap form with crispy forms
- Add branding and links to new frontend landing page

ref: helxplatform/development#664 helxplatform/development#666 helxplatform/development#663 helxplatform/development#655 helxplatform/development#699

### CODE REVIEW

**Review by rencibuild — COMMENTED** [review]
- In appstore/Dockerfile, you remove installation of postgres and xmlsec1, are they no longer required?
- Is IRODS no longer needed?
- In appstore/appstore/settings/base.py, minor, but there's a typo in the spelling of "General"
- In appstore/core/views.py, at line 291, I added a custom handler404 to handle the case of  app pages that were reaped or failed for other reasons. Lines 291-292 put a separate template "private404.html" in for that case. If the updated code still calls this separate handler for app pages in this condition, I'm fine with it, otherwise, there needs to be provision for this scenario. I didn't see that happening anywhere but perhaps I missed it?

**Comment by n0mn0m** [comment]
> * In appstore/Dockerfile, you remove installation of postgres and xmlsec1, are they no longer required?
- Only postgres. We don't use Postgres just sqlite, so we should no need the dependency. Any app started by tycho from the appstore should handle database connections in that container.
> * Is IRODS no longer needed?
- Per this thread we are no longer supplying the irod login, so we wouldn't need the template https://github.com/helxplatform/appstore/pull/93#discussion_r605835773
> * In appstore/appstore/settings/base.py, minor, but there's a typo in the spelling of "General"
- 👍  I'll get that fixed
> * In appstore/core/views.py, at line 291, I added a custom handler404 to handle the case of  app pages that were reaped or failed for other reasons. Lines 291-292 put a separate template "private404.html" in for that case. If the updated code still calls this separate handler for app pages in this condition, I'm fine with it, otherwise, there needs to be provision for this scenario. I didn't see that happening anywhere but perhaps I missed it?
- That template didn't exist, and based on the code would serve for a 404 error when `private` is in the path. Without the template/html file existing it errored out. What was supposed to be different about the template from the standard 404 template, and what was special about private being in the route? Happy to add this back.

**Review by muralikarthikk — APPROVED** [review]

**Review by ismagilani — APPROVED** [review]

**Comment by rencibuild** [comment]
> "That template didn't exist, and based on the code would serve for a 404 error when private is in the path. "

Here's the original private404.html:
```
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{% trans "404 Not Found" %}{% endblock %}

{% block content %}

<h1>{% trans "404 Not Found" %}</h1>

<p>
  {% trans "App running at " %} {{ req_path }} {% trans " is no longer available." %}

<p>
<p>
Return to <a href="/apps">{% trans " Apps " %}</a> {% trans "page." %}

{% endblock %}
```

> "What was supposed to be different about the template from the standard 404 template"

It indicated the previously running app (gave address) was no longer available and gave a link back to the app page. This was a request from Steve.

> "what was special about private being in the route?" 

The urls for apps (eg jupyter notebook, cloudtop) started by appstore always contain "private"

**Comment by n0mn0m** [comment]
> > "That template didn't exist, and based on the code would serve for a 404 error when private is in the path. "
> 
> Here's the original private404.html:
> 
> ```
> {% extends "base.html" %}
> 
> {% load i18n %}
> {% load bootstrap %}
> 
> {% block head_title %}{% trans "404 Not Found" %}{% endblock %}
> 
> {% block content %}
> 
> <h1>{% trans "404 Not Found" %}</h1>
> 
> <p>
>   {% trans "App running at " %} {{ req_path }} {% trans " is no longer available." %}
> 
> <p>
> <p>
> Return to <a href="/apps">{% trans " Apps " %}</a> {% trans "page." %}
> 
> {% endblock %}
> ```
> 
> > "What was supposed to be different about the template from the standard 404 template"
> 
> It indicated the previously running app (gave address) was no longer available and gave a link back to the app page. This was a request from Steve.
> 
> > "what was special about private being in the route?"
> 
> The urls for apps (eg jupyter notebook, cloudtop) started by appstore always contain "private"

Thanks Chuck. I can't find the file in git history, and I wasn't triggering that behavior so I thought it was a unexercised path.

```code
appstore on  alexander/cleanup [!?] via 🐍 v3.9.2 (appstore-dj3)on ☁️  
❯ git log --all --full-history -- "**/private404.*"


appstore on  alexander/cleanup [!?] via 🐍 v3.9.2 (appstore-dj3)on ☁️  
❯ git log --all --full-history -- "**/private404.html"


appstore on  alexander/cleanup [!?] via 🐍 v3.9.2 (appstore-dj3)on ☁️  
❯ git log --all --full-history -- "private404.html"
```

I'll add back the `private` 404 functionality.

**Review by cnbennett3 — APPROVED** [review]

**Comment by n0mn0m** [comment]
@cnbennett3 updated with the 404 functionality if you want to double check that. Thanks for the catch.

**Review by cnbennett3 — APPROVED** [review]

**Pull request merged**
