### PR TITLE
Fix ALLOW_DJANGO_LOGIN.

### PR DESCRIPTION
**Pull request by cnbennett3**

### CODE REVIEW

**Review by ismagilani — APPROVED** [review]

**Review by n0mn0m — COMMENTED** [review]
Do we intentionally use a string instead of a `bool` in `settings/base.py` for `ALLOW_DJANGO_LOGIN`, or is it just something that happened in the past? I know these are the only two places it's used today, but seems like the kind of thing that could pop up again where string match vs bool can behave differently.

**Comment by ismagilani** [comment]
> Do we intentionally use a string instead of a `bool` in `settings/base.py` for `ALLOW_DJANGO_LOGIN`, or is it just something that happened in the past? I know these are the only two places it's used today, but seems like the kind of thing that could pop up again where string match vs bool can behave differently.

@n0mn0m I thought env variables were string by default not boolean?

**Comment by n0mn0m** [comment]
> > Do we intentionally use a string instead of a `bool` in `settings/base.py` for `ALLOW_DJANGO_LOGIN`, or is it just something that happened in the past? I know these are the only two places it's used today, but seems like the kind of thing that could pop up again where string match vs bool can behave differently.
> 
> @n0mn0m I thought env variables were string by default not boolean?

They are, but in `settings/base.py` we can convert it for clarity:

```python
ALLOW_DJANGO_LOGIN = os.environ.get('ALLOW_DJANGO_LOGIN',
                                    "True" if DEV_PHASE == "local" or DEV_PHASE == 'stub' else "False").lower()
```

That could be:

```python
from distutils.util import strtobool

ALLOW_DJANGO_LOGIN = bool(strtobool(os.environ.get('ALLOW_DJANGO_LOGIN',
                                    'True' if DEV_PHASE == "local" or DEV_PHASE == 'stub'
                                    else 'False')))
```

May not be what we want to do, but I wanted to check. I know `strtobool` came up earlier this week in scrum too, which also helps if `ALLOW_DJANGO_LOGIN` was set to a non `true|false` value somehow.

```python
>>> import os
>>> from distutils.util import strtobool
>>> DEV_PHASE = 'local'
>>> os.environ['ALLOW_DJANGO_LOGIN'] = 'foo'
>>> os.environ['ALLOW_DJANGO_LOGIN']
'foo'

>>> ALLOW_DJANGO_LOGIN = bool(strtobool(os.environ.get('ALLOW_DJANGO_LOGIN',
                                    'True' if DEV_PHASE == "local" or DEV_PHASE == 'stub'
                                    else 'False')))
                                              
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/util.py", line 302, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
    
ValueError: invalid truth value 'foo'

>>> os.environ['ALLOW_DJANGO_LOGIN'] = 'true'
>>> ALLOW_DJANGO_LOGIN = bool(strtobool(os.environ.get('ALLOW_DJANGO_LOGIN',
                                    'True' if DEV_PHASE == "local" or DEV_PHASE == 'stub'
                                    else 'False')))
>>> ALLOW_DJANGO_LOGIN
True
>>> type(ALLOW_DJANGO_LOGIN)
<class 'bool'>
>>> os.environ['ALLOW_DJANGO_LOGIN'] = 'False'
>>> ALLOW_DJANGO_LOGIN = bool(strtobool(os.environ.get('ALLOW_DJANGO_LOGIN',
                                    'True' if DEV_PHASE == "local" or DEV_PHASE == 'stub'
                                    else 'False')))
>>> ALLOW_DJANGO_LOGIN
False
>>>type(ALLOW_DJANGO_LOGIN)
<class 'bool'>
```

And we get to a `bool` class/type for condition checking.

**Comment by cnbennett3** [comment]
The short answer is, it gets a lot more complicated when you get kubernetes and helm involved. Kubernetes uses configMaps, which only allow strings, so any bool-ness gets lost by the time you get to the cluster. I did originally try your suggestion and it didn't work for this reason. For the DEBUG case, the only thing we found that would work is setting it to "".

**Comment by n0mn0m** [comment]
> The short answer is, it gets a lot more complicated when you get kubernetes and helm involved. Kubernetes uses configMaps, which only allow strings, so any bool-ness gets lost by the time you get to the cluster. I did originally try your suggestion and it didn't work for this reason. For the DEBUG case, the only thing we found that would work is setting it to "".

Good to know. Thanks for the insight there. It's odd, because the `bool` type (in the example above) is coming from Python based on environment strings, but I understand there are a lot of moving parts in the deployed environment. If the deployment environment has impacts that prevents us from using `bool` types then this looks good to me.

**Review by muralikarthikk — APPROVED** [review]

**Comment by ismagilani** [comment]
@n0mn0m can you approve this PR?

**Comment by n0mn0m** [comment]
> @n0mn0m can you approve this PR?

I don't think I can after it's merged, but it's merged 😃

**Comment by ismagilani** [comment]
Yes I was able to.

**Pull request merged**
