### PR TITLE
Update tycho version as a result of octave work. 

### PR DESCRIPTION
**Pull request by ismagilani**

### CODE REVIEW

**Comment by n0mn0m** [comment]
@ismagilani  does Tycho need to be bumped in `requirements.txt` and `setup.cfg`?

**Comment by n0mn0m** [comment]
@ismagilani if this is just a version bump for appstore since `tycho` was bumped in `develop` we can close this as my latest pr bumped to `dev5` and is in `develop` now.

**Comment by ismagilani** [comment]
@n0mn0m we can take that route. Although I need to change tycho once more since somehow we had a discrepancy in version.  I saw a 1.0.19 version in tycho so I bumped it to 1.0.20 but it actually should've been 1.0.15 as @muralikarthikk checked pypi and latest version was 1.0.14.  So I am going to add a 1.0.15 for tycho in pypi and then update appstore files again and add them to this PR if that works for you?

**Comment by n0mn0m** [comment]
@ismagilani that sounds great to me, thanks :)

**Review by n0mn0m — APPROVED** [review]

**Pull request merged**
